# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: CICD For Backend On master branch

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: self-hosted
    
    strategy:
      matrix:
        node-version: [16.x]
        
    steps:    
      - name: Checkout code
        uses: actions/checkout@v3
       
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Install pm2
        run: npm install pm2 -g
        
      - run: npm install 
      
      - name: Restart pm2 process
        run: pm2 restart npm -- start    
